#
# This file contains configuration flags to customize your site
#

highlighter: rouge
permalink: /:title/
markdown: kramdown

# The release of Jekyll Now that you're using
version: v1.0.0

gems:
    - jekyll-sitemap
    - jekyll-redirect-from

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://www.freefour.com

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: css/_scss
  style: :expanded # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - serve.sh
    - update.sh
    - CNAME