#
# This file contains configuration flags to customize your site
#

highlighter: pygments
permalink: /:title/
markdown: kramdown

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: css/_scss
  style: :expanded # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - serve.sh
    - update.sh